# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cpp_py_exchange_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cpp_py_exchange_data.proto',
  package='yy',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1a\x63pp_py_exchange_data.proto\x12\x02yy\"\x81\x01\n\x0bMsgToServer\x12%\n\x07msgMode\x18\x01 \x01(\x0e\x32\x14.yy.MsgToServer.Mode\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x11\n\timgBuffer\x18\x04 \x03(\x0c\"\x19\n\x04Mode\x12\x08\n\x04\x45XIT\x10\x00\x12\x07\n\x03RUN\x10\x01\"@\n\x0bMsgToClient\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x12\n\nactionType\x18\x03 \x01(\tb\x06proto3')
)



_MSGTOSERVER_MODE = _descriptor.EnumDescriptor(
  name='Mode',
  full_name='yy.MsgToServer.Mode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EXIT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUN', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=139,
  serialized_end=164,
)
_sym_db.RegisterEnumDescriptor(_MSGTOSERVER_MODE)


_MSGTOSERVER = _descriptor.Descriptor(
  name='MsgToServer',
  full_name='yy.MsgToServer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msgMode', full_name='yy.MsgToServer.msgMode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='yy.MsgToServer.width', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='yy.MsgToServer.height', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='imgBuffer', full_name='yy.MsgToServer.imgBuffer', index=3,
      number=4, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MSGTOSERVER_MODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=164,
)


_MSGTOCLIENT = _descriptor.Descriptor(
  name='MsgToClient',
  full_name='yy.MsgToClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='yy.MsgToClient.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='yy.MsgToClient.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actionType', full_name='yy.MsgToClient.actionType', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=230,
)

_MSGTOSERVER.fields_by_name['msgMode'].enum_type = _MSGTOSERVER_MODE
_MSGTOSERVER_MODE.containing_type = _MSGTOSERVER
DESCRIPTOR.message_types_by_name['MsgToServer'] = _MSGTOSERVER
DESCRIPTOR.message_types_by_name['MsgToClient'] = _MSGTOCLIENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgToServer = _reflection.GeneratedProtocolMessageType('MsgToServer', (_message.Message,), dict(
  DESCRIPTOR = _MSGTOSERVER,
  __module__ = 'cpp_py_exchange_data_pb2'
  # @@protoc_insertion_point(class_scope:yy.MsgToServer)
  ))
_sym_db.RegisterMessage(MsgToServer)

MsgToClient = _reflection.GeneratedProtocolMessageType('MsgToClient', (_message.Message,), dict(
  DESCRIPTOR = _MSGTOCLIENT,
  __module__ = 'cpp_py_exchange_data_pb2'
  # @@protoc_insertion_point(class_scope:yy.MsgToClient)
  ))
_sym_db.RegisterMessage(MsgToClient)


# @@protoc_insertion_point(module_scope)
